set(_CATKIN_CURRENT_PACKAGE "lab01_chatter")
set(lab01_chatter_VERSION "0.0.0")
set(lab01_chatter_MAINTAINER "dipto <dipto@todo.todo>")
set(lab01_chatter_PACKAGE_FORMAT "2")
set(lab01_chatter_BUILD_DEPENDS )
set(lab01_chatter_BUILD_EXPORT_DEPENDS )
set(lab01_chatter_BUILDTOOL_DEPENDS "catkin")
set(lab01_chatter_BUILDTOOL_EXPORT_DEPENDS )
set(lab01_chatter_EXEC_DEPENDS )
set(lab01_chatter_RUN_DEPENDS )
set(lab01_chatter_TEST_DEPENDS )
set(lab01_chatter_DOC_DEPENDS )
set(lab01_chatter_URL_WEBSITE "")
set(lab01_chatter_URL_BUGTRACKER "")
set(lab01_chatter_URL_REPOSITORY "")
set(lab01_chatter_DEPRECATED "")