set(_CATKIN_CURRENT_PACKAGE "lab06_gazebo")
set(lab06_gazebo_VERSION "0.0.0")
set(lab06_gazebo_MAINTAINER "dipto <dipto@todo.todo>")
set(lab06_gazebo_PACKAGE_FORMAT "2")
set(lab06_gazebo_BUILD_DEPENDS )
set(lab06_gazebo_BUILD_EXPORT_DEPENDS )
set(lab06_gazebo_BUILDTOOL_DEPENDS "catkin")
set(lab06_gazebo_BUILDTOOL_EXPORT_DEPENDS )
set(lab06_gazebo_EXEC_DEPENDS )
set(lab06_gazebo_RUN_DEPENDS )
set(lab06_gazebo_TEST_DEPENDS )
set(lab06_gazebo_DOC_DEPENDS )
set(lab06_gazebo_URL_WEBSITE "")
set(lab06_gazebo_URL_BUGTRACKER "")
set(lab06_gazebo_URL_REPOSITORY "")
set(lab06_gazebo_DEPRECATED "")