set(_CATKIN_CURRENT_PACKAGE "lab06_vision")
set(lab06_vision_VERSION "0.0.0")
set(lab06_vision_MAINTAINER "dipto <dipto@todo.todo>")
set(lab06_vision_PACKAGE_FORMAT "2")
set(lab06_vision_BUILD_DEPENDS )
set(lab06_vision_BUILD_EXPORT_DEPENDS )
set(lab06_vision_BUILDTOOL_DEPENDS "catkin")
set(lab06_vision_BUILDTOOL_EXPORT_DEPENDS )
set(lab06_vision_EXEC_DEPENDS )
set(lab06_vision_RUN_DEPENDS )
set(lab06_vision_TEST_DEPENDS )
set(lab06_vision_DOC_DEPENDS )
set(lab06_vision_URL_WEBSITE "")
set(lab06_vision_URL_BUGTRACKER "")
set(lab06_vision_URL_REPOSITORY "")
set(lab06_vision_DEPRECATED "")