set(_CATKIN_CURRENT_PACKAGE "lab06_description")
set(lab06_description_VERSION "0.0.0")
set(lab06_description_MAINTAINER "dipto <dipto@todo.todo>")
set(lab06_description_PACKAGE_FORMAT "2")
set(lab06_description_BUILD_DEPENDS )
set(lab06_description_BUILD_EXPORT_DEPENDS )
set(lab06_description_BUILDTOOL_DEPENDS "catkin")
set(lab06_description_BUILDTOOL_EXPORT_DEPENDS )
set(lab06_description_EXEC_DEPENDS )
set(lab06_description_RUN_DEPENDS )
set(lab06_description_TEST_DEPENDS )
set(lab06_description_DOC_DEPENDS )
set(lab06_description_URL_WEBSITE "")
set(lab06_description_URL_BUGTRACKER "")
set(lab06_description_URL_REPOSITORY "")
set(lab06_description_DEPRECATED "")