set(_CATKIN_CURRENT_PACKAGE "lab06_radeeb_control")
set(lab06_radeeb_control_VERSION "0.0.0")
set(lab06_radeeb_control_MAINTAINER "rjb102 <rjb102@todo.todo>")
set(lab06_radeeb_control_PACKAGE_FORMAT "2")
set(lab06_radeeb_control_BUILD_DEPENDS )
set(lab06_radeeb_control_BUILD_EXPORT_DEPENDS )
set(lab06_radeeb_control_BUILDTOOL_DEPENDS "catkin")
set(lab06_radeeb_control_BUILDTOOL_EXPORT_DEPENDS )
set(lab06_radeeb_control_EXEC_DEPENDS )
set(lab06_radeeb_control_RUN_DEPENDS )
set(lab06_radeeb_control_TEST_DEPENDS )
set(lab06_radeeb_control_DOC_DEPENDS )
set(lab06_radeeb_control_URL_WEBSITE "")
set(lab06_radeeb_control_URL_BUGTRACKER "")
set(lab06_radeeb_control_URL_REPOSITORY "")
set(lab06_radeeb_control_DEPRECATED "")