set(_CATKIN_CURRENT_PACKAGE "lab03_control")
set(lab03_control_VERSION "0.0.0")
set(lab03_control_MAINTAINER "dipto <dipto@todo.todo>")
set(lab03_control_PACKAGE_FORMAT "2")
set(lab03_control_BUILD_DEPENDS )
set(lab03_control_BUILD_EXPORT_DEPENDS )
set(lab03_control_BUILDTOOL_DEPENDS "catkin")
set(lab03_control_BUILDTOOL_EXPORT_DEPENDS )
set(lab03_control_EXEC_DEPENDS )
set(lab03_control_RUN_DEPENDS )
set(lab03_control_TEST_DEPENDS )
set(lab03_control_DOC_DEPENDS )
set(lab03_control_URL_WEBSITE "")
set(lab03_control_URL_BUGTRACKER "")
set(lab03_control_URL_REPOSITORY "")
set(lab03_control_DEPRECATED "")