<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="lab03">


    <!--
        Gazebo requires the following:
            An <inertia> element within each <link> (handled in adabot.main.xacro).
        It also useful to specify the following:
            A <gazebo> element for every <link>
                - Gazebo colors
                - DAE files for textures
                - sensor plugins
            A <gazebo> element for every <joint>
                - damping dynamics
                - actuator plugins
            A <link name="world" /> if the robot is rigidyly attached to the world
        By conventions, units should be specified in meters and kilograms.
    -->




    <gazebo>
        <!-- <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so"> -->
        <plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so">
            <!-- <robotNamespace>/lab03</robotNamespace>
            <robotSimType>gazebo_ros_control/DefaultRobotHWSim</robotSimType> -->
            <alwaysOn>true</alwaysOn>
            <updateRate>10</updateRate>
            <leftJoint>left_wheel_joint</leftJoint>
            <rightJoint>right_wheel_joint</rightJoint>
            <wheelSeparation>${(chassis_radius-wheel_radius)*2}</wheelSeparation>
            <wheelDiameter>${wheel_radius * 2}</wheelDiameter>
            <torque>20</torque>
            <commandTopic>cmd_vel</commandTopic>
            <odometryTopic>odom</odometryTopic>
            <odometryFrame>odom</odometryFrame>
            <robotBaseFrame>robot_chassis</robotBaseFrame>
            <legacyMode>false</legacyMode>
        </plugin>
    </gazebo>




    <!-- http://wiki.ros.org/simulator_gazebo/Tutorials/ListOfMaterials -->
    <xacro:macro name="gz_black_material" params="name">
        <gazebo reference="${name}">
            <material>Gazebo/FlatBlack</material>
        </gazebo>
    </xacro:macro>

    <xacro:macro name="gz_white_material" params="name">
        <gazebo reference="${name}">
            <material>Gazebo/White</material>
        </gazebo>
    </xacro:macro>

    <xacro:macro name="gz_blue_material" params="name">
        <gazebo reference="${name}">
            <material>Gazebo/Blue</material>
        </gazebo>
    </xacro:macro>

    <xacro:macro name="gz_red_material" params="name">
        <gazebo reference="${name}">
            <material>Gazebo/Red</material>
        </gazebo>
    </xacro:macro>




    <!-- Material frictions -->
    <xacro:macro name="gz_high_friction" params="name">
        <gazebo reference="${name}">
            <mu1 value="100.0" />
            <mu2 value="100.0" />
            <kp  value="10000000.0" />
            <kd  value="1.0" />
            <fdir1 value="1 0 0" />
        </gazebo>
    </xacro:macro>

    <xacro:macro name="gz_low_friction" params="name">
        <gazebo reference="${name}">
            <mu1 value="0.5" />
            <mu2 value="0.5" />
            <kp  value="10000000.0" />
            <kd  value="1.0" />
            <fdir1 value="1 0 0" />
        </gazebo>
    </xacro:macro>

    <!-- Camera -->
    <link name="camera_link">
      <collision>
        <origin xyz="0 0 0.02" rpy="0 0 0"/>
        <geometry>
          <box size="0.02 0.02 0.02"/>
        </geometry>
      </collision>

      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="0.1 0.1 0.1"/>
        </geometry>
        <material name="red"/>
      </visual>

      <inertial>
        <mass value="0.001" />
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <inertia ixx="0.00000015" ixy="0" ixz="0" iyy="0.00000015" iyz="0" izz="0.00000015" />
      </inertial>
    </link>

    <joint name="camera_joint" type="fixed">
        <axis xyz="0 0 0" />
        <origin xyz="0 0 0.1" rpy="0 0 0"/>
        <parent link="robot_chassis"/>
        <child link="camera_link"/>
    </joint>

     <!-- camera -->
    <gazebo reference="camera_link">
    <sensor type="camera" name="camera1">
      <update_rate>30.0</update_rate>
      <camera name="head">
        <horizontal_fov>1.3962634</horizontal_fov>
        <image>
          <width>800</width>
          <height>800</height>
          <format>R8G8B8</format>
        </image>
        <clip>
          <near>0.02</near>
          <far>300</far>
        </clip>
        <noise>
          <type>gaussian</type>
          <!-- Noise is sampled independently per pixel on each frame.
               That pixel's noise value is added to each of its color
               channels, which at that point lie in the range [0,1]. -->
          <mean>0.0</mean>
          <stddev>0.007</stddev>
        </noise>
      </camera>
      <plugin name="camera_controller" filename="libgazebo_ros_camera.so">
        <alwaysOn>true</alwaysOn>
        <updateRate>0.0</updateRate>
        <cameraName>lab03/camera1</cameraName>
        <imageTopicName>image_raw</imageTopicName>
        <cameraInfoTopicName>camera_info</cameraInfoTopicName>
        <frameName>camera_link</frameName>
        <hackBaseline>0.07</hackBaseline>
        <distortionK1>0.0</distortionK1>
        <distortionK2>0.0</distortionK2>
        <distortionK3>0.0</distortionK3>
        <distortionT1>0.0</distortionT1>
        <distortionT2>0.0</distortionT2>
      </plugin>
    </sensor>
    </gazebo>

</robot>